[tool.poetry]
name = "agentic-demo"
version = "0.1.0"
description = "Demo project scaffold"
authors = ["Agent <agent@example.com>"]
readme = "README.md"
packages = [{ include = "agentic_demo", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.13,<4.0"
pytest = {version = ">=7.4", optional = true}
pytest-cov = {version = ">=4.1", optional = true}
pytest-asyncio = {version = ">=0.23", optional = true}
langgraph = "*"
openai = "*"
perplexity-api = "*"
pysqlite3-binary = "*" # provides sqlite3
python-docx = "*"
weasyprint = "*"
fastapi = "*"
uvicorn = "*"
python-dotenv = "*"

[tool.poetry.group.dev.dependencies]
black = ">=24.3"
ruff = ">=0.4"
mypy = ">=1.8"
bandit = ">=1.7"
pip-audit = ">=2.7"

[tool.poetry.extras]
test = ["pytest", "pytest-cov", "pytest-asyncio"]

[build-system]
requires = ["poetry-core>=1.8.1"]
build-backend = "poetry.core.masonry.api"

[tool.black]

[tool.ruff]
line-length = 88

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true
exclude = ["tests/"]
