[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "agentic-demo"
version = "0.1.0"
requires-python = ">=3"
dependencies = [
    "openai>=1.25.0",
    "tavily-python>=0.7.10",
    "python-dotenv>=1.1.1",
    "langgraph>=0.6.2",
    "python-docx",
]

[project.optional-dependencies]
test = [
    "pytest>=7.4",
    "pytest-cov>=4.1",
    "pytest-asyncio>=0.23",
]
dev = [
    "black>=24.3",
    "ruff>=0.4",
    "mypy>=1.8",
]

[tool.setuptools]
packages = [
    "app",
    "openai_stub",
    "scripts",
    "web",
]


[tool.black]

[tool.ruff]
line-length = 88

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true
exclude = ["tests/"]
