[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "agentic-demo"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.98.0",
    "tavily-python>=0.7.10",
    "python-dotenv>=1.1.1",
]
