name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'poetry'
          cache-dependency-path: poetry.lock
      - uses: abatilo/actions-poetry@v4
        with:
          poetry-version: '2.1.3'
      - run: poetry install --no-interaction --no-ansi --no-root --with dev --extras test
      - run: poetry run pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'poetry'
          cache-dependency-path: poetry.lock
      - uses: abatilo/actions-poetry@v4
        with:
          poetry-version: '2.1.3'
      - run: poetry install --no-interaction --no-ansi --no-root --with dev --extras test
      - run: poetry run pytest --maxfail=1 --disable-warnings -q
