name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.8.3'
      - run: poetry install --with dev -E test
      - run: poetry run black --check .
      - run: poetry run ruff .
      - run: poetry run mypy .
      - run: poetry run bandit -r src -ll
      - run: poetry run pip-audit

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.8.3'
      - run: poetry install -E test
      - run: poetry run pytest --cov
